spec: Require the lib when installing the cli
The previous version didn't require the library, and so would fail with the
following error.

    Traceback (most recent call last):
       File "/usr/bin/rhsecapi", line 25, in <module>
        import rhsda
    ModuleNotFoundError: No module named 'rhsda'